[general]
import = [
        "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
]

[window]
title = "Terminal - alacritty"
decorations_theme_variant = "Dark"

[scrolling]
multiplier = 7

[colors]
cursor = { text = "CellBackground", cursor="0xff7b72" }
selection = { text = "CellBackground", cursor="0xff7b72" }

[bell]
duration = 0
color = "0xff7b72"
animation = "EaseOutQuint"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500
blink_timeout = 15

[font]
size = 16.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"
